task_app/config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

 

  resources :users do
    resources :messages 
  end
  resources :users
  resources :tasks

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  delete '/logout' => "sessions#delete"
 

end

task_app/app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
end

task_app/app/models/task.rb
class Task < ActiveRecord::Base
	has_many :taskings
	has_many :users, through: :taskings
end

task_app/app/models/tasking.rb
class Tasking < ActiveRecord::Base
	belongs_to :user
	belongs_to :task
end

task_app/app/models/user.rb
class User < ActiveRecord::Base
	has_many :taskings
	has_many :tasks, through: :taskings
	has_many :messages

	has_secure_password
end

task_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  	def current_user
  		User.find(session[:user_id]) if session[:user_id]
  	end

  	def authenticate
  		unless current_user.present?
  			redirect_to login_path
  	end

  end
end

task_app/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def index
		@user = User.find(params[:user_id])
		@messages = @user.messages
	end

	def new
		@user = User.find(params[:user_id])
		@message = Message.new
	end

	def create
		@user = User.find(params[:user_id])
		@message = Message.create(message_params) 
		redirect_to user_path(@user)
	end

	def show
		@message = Message.find(params[:id])
	end

	def destroy
		@message = Message.find(params[:id])
		@message.delete
		redirect_to @message.user
	end

	private
	def message_params
		params
		.require(:message)
		.permit(:content, :attachment, :sender_id)
		.merge({user_id: params[:user_id]})
	end

end

task_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # direct to profile page
      
    else
      # create error msg
      render new
    end
  end

  def destroy

  end

end

task_app/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
# authentication callback before action, no authentication required to the excepts ones
 # before_action :authenticate, except: [:index]

# GET /tasks
  # def index
  #   if params[:user_id]
  #     @tasks = Task.where({user_id: params[:user_id]})
  #   else
  #     @tasks = Task.all
  #   end
  # end

  def new
    @task = Task.new
  end

# GET /tasks/new
  def create
    Task.create(task_params)
    redirect_to tasks_path
  end

# GET /tasks/:id - show task
  def show
    @task = Task.find(params[:id])
  end

# GET /tasks/:id/edit
  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to tasks_path
  end

# DELETE /tasks/:id
  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:title, :content, :duedate, :location, :user_id)
  end
end

task_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user = User.where({user_id: params[:name]})

	end
	def new
  @user = User.new
	end

	def create
		@user = User.create(user_params)
  		if @user.save
  			session[:user_id] = @user_id
	  			redirect_to  user_post
	  			else
					render template: "sessions/new"
  		end
  	end
  

  

private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end


end

task_app/app/helpers/application_helper.rb
module ApplicationHelper
end

task_app/app/helpers/tasks_helper.rb
module TasksHelper
end

task_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

task_app/app/views/messages/_form.html.erb
<h1>Write a New Message</h1>
<%= f.label :content %>
<%= f.text_field :content %>
<%= f.label :attachment %>
<%= f.text_field :attachment %>
<%= f.label :sender_id %>
<%= f.text_field :sender_id %>
<%= f.submit %>

task_app/app/views/messages/index.html.erb
<h1>All Messages for <%= @user.name %></h1>
<ul>
	<% @messages.each do |message| %>
	<li>
		<%= link_to message.content, user_message_path(message) %>
	</li>
	<% end %>

	<%= link_to 'Compose a New Message', new_user_message(@user) %>
</ul>

task_app/app/views/messages/new.html.erb
<%= form_for([@user, @message]) do |f| %>
<%= render 'form', f: f %>
<% end %>

task_app/app/views/messages/show.html.erb
<h1> Here is you message</h1>
<p><%= @message.content %></p>
<p><%= @message.attachment %></p>
<p><%= @message.sender_id %></p>

task_app/app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title, 'Title'%>
  <%= f.text_field :title, 'Title', placeholder:'Title'%>
  <%= f.hidden_field :user_id, value:session[:user_id]%>
  <%= f.label :content, 'Content'%>
  <%= f.text_field :content, placeholder: 'Content' %>
  <%= f.label :duedate, 'Duedate'%>
  <%= f.date_field :duedate %>
  <%= f.label :location, 'Location'%>
  <%= f.text_field :location, placeholder:'Location'%>
  <%= f.submit %>
<% end %>

task_app/app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<form action="/tasks" method="GET">
  <input type="text" placeholder="<%= @task.title%>" name="title">
  <input type="text" placeholder="<%= @task.content%>" name="content">
  <input type="date" placeholder="<%= @task.duedate%>" name="duedate">
  <input type="text" placeholder="<%= @task.location%>" name="location">
  <button>Edit task</button>

</form>

task_app/app/views/tasks/index.html.erb
<% @task.each do |t| %>
  <%= link_to t.title %>
<% end %>

task_app/app/views/tasks/new.html.erb
<h1>Make a new task</h1>
<form action="/tasks" method="GET">
<input type="text" placeholder="Title" name="title">
<input type="text" placeholder="Content" name="content">
<input type="date" name="duedate">
<input type="text" placeholder="Location" name="location">
<button>Add task</button>
</form>

task_app/app/views/tasks/show.html.erb
<h2><%= @task.title%></h2>
<p><%= @task.duedate%></p>
<p><%= @task.content%></p>
<p><%= @task.location%></p>


<%= link_to 'Edit task', edit_task_path %>

<%= link_to 'Delete task', task_path, method: :delete %>

task_app/app/views/users/index.html.erb
<h1><%= @user.name %></h1>

<h1><%= @user.email %></h1>

task_app/app/views/users/new.html.erb
<h4>Start Tasking</h4>

<!--  -->

      <%= form_for @user do |f| %>
      <%= f.text_field :name, placeholder: 'Name' %></br>
      <%= f.text_field :email, placeholder: 'Email' %></br>
      <%= f.password_field :password, placeholder: 'Password' %></br>
      <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation' %></br>
      <%= f.button 'Signup' %>
      <% end %>	